-- Generated from specs/fairino-field-device-handoff-v4-existing-project.json.
-- Do not edit this file by hand; run: npm run generate:m31-io
-- Shared data: 0.1.0-rc.23 / fd26d46cdb2bc23d41874e210aa2ed4791e793a7

M31_DI_COUNT = 32
M31_DO_COUNT = 16
M31_DI_SAFETY_DIAGNOSTIC = 0

-- Zero-based Modbus coil addresses.
DO_GRIPPER_CLOSE = 0
DO_CLAMP_CLOSE = 1
DO_LAMP_GREEN = 2
DO_LAMP_ORANGE = 3
DO_LAMP_RED = 4
DO_CHECK_VALVE_PRESS = 5
DO_CHECK_VALVE_FEED = 6
DO_GLUE_TRIGGER = 7
DO_LAMP_BLUE = 8
DO_BUZZER = 9

-- Zero-based Modbus discrete-input addresses.
DI_CHECK_VALVE_PICK_PRESENT = 1
DI_GRIPPER_OPEN = 2
DI_GRIPPER_FILTER_POSITION = 3
DI_GRIPPER_CHECK_VALVE_POSITION = 4
DI_FILTER_CLAMP_OPEN = 5
DI_FILTER_CLAMP_CLOSED = 6
DI_PRESS_HOME = 7
DI_PRESS_INSERTED = 8
DI_CHECK_VALVE_GATE_OPEN = 9
DI_CHECK_VALVE_GATE_CLOSED = 10
DI_AIR_PRESSURE_OK = 11
DI_DRYING_POSITION_OCCUPIED = 12
DI_FILTER_DISPENSER_1_PRESENT = 16
DI_FILTER_DISPENSER_2_PRESENT = 17
DI_FILTER_DISPENSER_3_PRESENT = 18
DI_FILTER_DISPENSER_4_PRESENT = 19
DI_FILTER_DISPENSER_5_PRESENT = 20
DI_FILTER_DISPENSER_6_PRESENT = 21

FILTER_DISPENSER_INPUTS = {
    DI_FILTER_DISPENSER_1_PRESENT,
    DI_FILTER_DISPENSER_2_PRESENT,
    DI_FILTER_DISPENSER_3_PRESENT,
    DI_FILTER_DISPENSER_4_PRESENT,
    DI_FILTER_DISPENSER_5_PRESENT,
    DI_FILTER_DISPENSER_6_PRESENT,
}

M31_IO_METADATA = {
    ["DO_GRIPPER_CLOSE"] = {
        device_name = "Magneetventiel 1",
        process_location = "Grijper",
        function_description = "Opent en sluit de pneumatische productgrijper",
        controller_id = "existing-m31-do-expansion",
        channel_id = "DO1",
        modbus_address = 0,
        safe_state = "de-energized",
    },
    ["DO_CLAMP_CLOSE"] = {
        device_name = "Magneetventiel 2",
        process_location = "Filterklem",
        function_description = "Klemt het filter vast en geeft het weer vrij",
        controller_id = "existing-m31-do-expansion",
        channel_id = "DO2",
        modbus_address = 1,
        safe_state = "de-energized",
    },
    ["DO_LAMP_GREEN"] = {
        device_name = "Signaaltoren 1",
        process_location = "Robotcel",
        function_description = "Geeft de machine-status visueel en akoestisch weer",
        controller_id = "existing-m31-do-expansion",
        channel_id = "DO3",
        modbus_address = 2,
        safe_state = "off",
    },
    ["DO_LAMP_ORANGE"] = {
        device_name = "Signaaltoren 1",
        process_location = "Robotcel",
        function_description = "Geeft de machine-status visueel en akoestisch weer",
        controller_id = "existing-m31-do-expansion",
        channel_id = "DO4",
        modbus_address = 3,
        safe_state = "off",
    },
    ["DO_LAMP_RED"] = {
        device_name = "Signaaltoren 1",
        process_location = "Robotcel",
        function_description = "Geeft de machine-status visueel en akoestisch weer",
        controller_id = "existing-m31-do-expansion",
        channel_id = "DO5",
        modbus_address = 4,
        safe_state = "off",
    },
    ["DO_CHECK_VALVE_PRESS"] = {
        device_name = "Magneetventiel 3",
        process_location = "Keerkleppers",
        function_description = "Beweegt de perscilinder voor het inpersen van de keerklep",
        controller_id = "existing-m31-do-expansion",
        channel_id = "DO6",
        modbus_address = 5,
        safe_state = "de-energized",
    },
    ["DO_CHECK_VALVE_FEED"] = {
        device_name = "Magneetventiel 4",
        process_location = "Keerklepdispenser",
        function_description = "Bedient de geteste gecombineerde keerkleptoevoer en vrijgave",
        controller_id = "existing-m31-do-expansion",
        channel_id = "DO7",
        modbus_address = 6,
        safe_state = "de-energized",
    },
    ["DO_GLUE_TRIGGER"] = {
        device_name = "Lijmdispenser 1",
        process_location = "Lijmstation",
        function_description = "Doseert lijm na een potentiaalvrij extern startsignaal",
        controller_id = "existing-m31-do-expansion",
        channel_id = "DO8",
        modbus_address = 7,
        safe_state = "start-contact-open",
    },
    ["DO_LAMP_BLUE"] = {
        device_name = "Signaaltoren 1",
        process_location = "Robotcel",
        function_description = "Geeft de machine-status visueel en akoestisch weer",
        controller_id = "existing-m31-do-expansion",
        channel_id = "DO9",
        modbus_address = 8,
        safe_state = "off",
    },
    ["DO_BUZZER"] = {
        device_name = "Signaaltoren 1",
        process_location = "Robotcel",
        function_description = "Geeft de machine-status visueel en akoestisch weer",
        controller_id = "existing-m31-do-expansion",
        channel_id = "DO10",
        modbus_address = 9,
        safe_state = "off",
    },
    ["DI_CHECK_VALVE_PICK_PRESENT"] = {
        device_name = "Glasvezelsensor 1",
        process_location = "Keerklep-pickpositie",
        function_description = "Detecteert of een keerklep gereedligt op de pickpositie",
        controller_id = "existing-m31-di-host",
        channel_id = "DI2",
        modbus_address = 1,
        safe_state = "inactive",
    },
    ["DI_GRIPPER_OPEN"] = {
        device_name = "Cilindersensor 1",
        process_location = "Grijper",
        function_description = "Detecteert dat de grijpercilinder volledig geopend is",
        controller_id = "existing-m31-di-host",
        channel_id = "DI3",
        modbus_address = 2,
        safe_state = "inactive",
    },
    ["DI_GRIPPER_FILTER_POSITION"] = {
        device_name = "Cilindersensor 2",
        process_location = "Grijper",
        function_description = "Detecteert de afgestelde grijpercilinderstand voor een correct geklemd filter",
        controller_id = "existing-m31-di-host",
        channel_id = "DI4",
        modbus_address = 3,
        safe_state = "inactive",
    },
    ["DI_GRIPPER_CHECK_VALVE_POSITION"] = {
        device_name = "Cilindersensor 3",
        process_location = "Grijper",
        function_description = "Detecteert de afgestelde grijpercilinderstand voor een correct geklemde keerklep",
        controller_id = "existing-m31-di-host",
        channel_id = "DI5",
        modbus_address = 4,
        safe_state = "inactive",
    },
    ["DI_FILTER_CLAMP_OPEN"] = {
        device_name = "Cilindersensor 4",
        process_location = "Filterklem",
        function_description = "Detecteert de volledig geopende eindstand van de filterklem",
        controller_id = "existing-m31-di-host",
        channel_id = "DI6",
        modbus_address = 5,
        safe_state = "inactive",
    },
    ["DI_FILTER_CLAMP_CLOSED"] = {
        device_name = "Cilindersensor 5",
        process_location = "Filterklem",
        function_description = "Detecteert de volledig gesloten eindstand van de filterklem",
        controller_id = "existing-m31-di-host",
        channel_id = "DI7",
        modbus_address = 6,
        safe_state = "inactive",
    },
    ["DI_PRESS_HOME"] = {
        device_name = "Cilindersensor 6",
        process_location = "Keerkleppers",
        function_description = "Detecteert de teruggetrokken thuisstand van de perscilinder",
        controller_id = "existing-m31-di-host",
        channel_id = "DI8",
        modbus_address = 7,
        safe_state = "inactive",
    },
    ["DI_PRESS_INSERTED"] = {
        device_name = "Cilindersensor 7",
        process_location = "Keerkleppers",
        function_description = "Detecteert de volledig ingeperste eindstand van de perscilinder",
        controller_id = "existing-m31-di-host",
        channel_id = "DI9",
        modbus_address = 8,
        safe_state = "inactive",
    },
    ["DI_CHECK_VALVE_GATE_OPEN"] = {
        device_name = "Cilindersensor 8",
        process_location = "Keerklepschuif",
        function_description = "Detecteert de volledig geopende eindstand van de keerklepschuif",
        controller_id = "existing-m31-di-host",
        channel_id = "DI10",
        modbus_address = 9,
        safe_state = "inactive",
    },
    ["DI_CHECK_VALVE_GATE_CLOSED"] = {
        device_name = "Cilindersensor 9",
        process_location = "Keerklepschuif",
        function_description = "Detecteert de volledig gesloten eindstand van de keerklepschuif",
        controller_id = "existing-m31-di-host",
        channel_id = "DI11",
        modbus_address = 10,
        safe_state = "inactive",
    },
    ["DI_AIR_PRESSURE_OK"] = {
        device_name = "Druksensor 1",
        process_location = "Pneumatische hoofdtoevoer",
        function_description = "Bewaakt of voldoende persluchtdruk voor de machine beschikbaar is",
        controller_id = "existing-m31-di-host",
        channel_id = "DI12",
        modbus_address = 11,
        safe_state = "inactive-low-pressure-or-sensor-fault",
    },
    ["DI_DRYING_POSITION_OCCUPIED"] = {
        device_name = "Glasvezelsensor 2",
        process_location = "Droog- en afvoerpositie",
        function_description = "Detecteert of een product aanwezig is op de droog- en afvoerpositie",
        controller_id = "existing-m31-di-host",
        channel_id = "DI13",
        modbus_address = 12,
        safe_state = "inactive",
    },
    ["DI_FILTER_DISPENSER_1_PRESENT"] = {
        device_name = "Fotocelsensor 1",
        process_location = "Filterdispenser 1",
        function_description = "Detecteert of een filter beschikbaar is in filterdispenser 1",
        controller_id = "existing-m31-di-expansion",
        channel_id = "DI1",
        modbus_address = 16,
        safe_state = "inactive",
    },
    ["DI_FILTER_DISPENSER_2_PRESENT"] = {
        device_name = "Fotocelsensor 2",
        process_location = "Filterdispenser 2",
        function_description = "Detecteert of een filter beschikbaar is in filterdispenser 2",
        controller_id = "existing-m31-di-expansion",
        channel_id = "DI2",
        modbus_address = 17,
        safe_state = "inactive",
    },
    ["DI_FILTER_DISPENSER_3_PRESENT"] = {
        device_name = "Fotocelsensor 3",
        process_location = "Filterdispenser 3",
        function_description = "Detecteert of een filter beschikbaar is in filterdispenser 3",
        controller_id = "existing-m31-di-expansion",
        channel_id = "DI3",
        modbus_address = 18,
        safe_state = "inactive",
    },
    ["DI_FILTER_DISPENSER_4_PRESENT"] = {
        device_name = "Fotocelsensor 4",
        process_location = "Filterdispenser 4",
        function_description = "Detecteert of een filter beschikbaar is in filterdispenser 4",
        controller_id = "existing-m31-di-expansion",
        channel_id = "DI4",
        modbus_address = 19,
        safe_state = "inactive",
    },
    ["DI_FILTER_DISPENSER_5_PRESENT"] = {
        device_name = "Fotocelsensor 5",
        process_location = "Filterdispenser 5",
        function_description = "Detecteert of een filter beschikbaar is in filterdispenser 5",
        controller_id = "existing-m31-di-expansion",
        channel_id = "DI5",
        modbus_address = 20,
        safe_state = "inactive",
    },
    ["DI_FILTER_DISPENSER_6_PRESENT"] = {
        device_name = "Fotocelsensor 6",
        process_location = "Filterdispenser 6",
        function_description = "Detecteert of een filter beschikbaar is in filterdispenser 6",
        controller_id = "existing-m31-di-expansion",
        channel_id = "DI6",
        modbus_address = 21,
        safe_state = "inactive",
    },
}
